
services:
  web:
    container_name: multicycle_app   # TODO: chang me for new instance
    build: .
#    image: "traefik/whoami"
    environment:
      SHOPIFY_APP_URL: "https://multicycle.cpro-server.de"
      HOST: "0.0.0.0"
      SHOPIFY_API_KEY: "98095151d80690ec33257c08a702f377"
      SHOPIFY_API_SECRET: "747c37e9a36b8b3ec52b463cb8be9240"
      SCOPES: "write_products,write_orders,read_orders"
      DATABASE_URL: "mysql://root:oY8io2Shshoo9Eix@multicycle_db:3306/multicycle" # TODO: change me>
    labels:
      - traefik.enable=true
      - traefik.http.routers.multicycle.rule=Host(`multicycle.cpro-server.de`) # TODO: change me fo>
      - traefik.http.routers.multicycle.entrypoints=websecure
      - traefik.http.routers.multicycle.tls.certresolver=letsencrypt
 #   - traefik.http.services.e-bike.loadbalancer.server.port=3000
    restart: unless-stopped
    networks:
      - web
      - intern
# might be needed, but seems to work without
#    dns:
#      - 8.8.8.8
  db:
    container_name: multicycle_db # TODO: change me for new instance
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
    image: mariadb:10
    restart: unless-stopped
    volumes:
      - ../databaseData/multicycle:/var/lib/mysql  # TODO: change me for new instnaces
    environment:
      - MARIADB_INITDB_SKIP_TZINFO=true
        #  - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=oY8io2Shshoo9Eix  # TODO: you may change me
    networks:
      - intern

networks:
  web:
    external: true
  intern:
    external: false

