# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "consors-f-multicycle"
client_id = "98095151d80690ec33257c08a702f377"
application_url = "https://cons-6a9dc71762e0.herokuapp.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_orders"

[auth]
redirect_urls = [
  "https://cons-6a9dc71762e0.herokuapp.com/auth/callback",
  "https://cons-6a9dc71762e0.herokuapp.com/auth/shopify/callback",
  "https://cons-6a9dc71762e0.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "helge-test.myshopify.com"
